on:
  schedule:
    - cron: "0 7 * * 1-5"
  push:
    branches:
      - main
      - master
    

name: update-data

jobs:
  R-CMD-check:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: [4.0.3]
    steps:
      - uses: actions/checkout@v2

      - name: Instalar R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1

      - name: Cache R packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-shinydoc
          restore-keys: |
            ${{ runner.os }}-

      - name: Instalar dependencias
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages(c("BETS", "usethis", "rsconnect"), type = "binary")
        shell: Rscript {0}
      
      - name: Atualizando dados
        run: |
          source('data-raw/series.R')
        shell: Rscript {0}
      
      - name: Conectando ao ShinyApps
        env:
          SHINY_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          shiny_token = Sys.getenv("SHINYAPPS_TOKEN")
          shiny_secret = Sys.getenv("SHINYAPPS_SECRET")
          rsconnect::setAccountInfo(name='albersonmiranda', token=shiny_token, secret=shiny_secret)
        shell: Rscript {0}

      - name: Deploy to ShinyApps
        run: |
          rsconnect::deployApp(forceUpdate = getOption("rsconnect.force.update.apps", TRUE))
        shell: Rscript {0}
