on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 7 * * 1-5"

name: update-data

jobs:
  update-data:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.0.3']
    steps:
      - uses: actions/checkout@v2

      - name: Instalar R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}

      - name: change macos locale
        run: |
          cd /usr/share/locale
          sudo cp -R pt_BR.UTF-8 pt_BR

      - name: change R locale
        run: Sys.setlocale("LC_TIME", "pt_BR.UTF-8")
        shell: Rscript {0}

      - name: Cache R packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-shinydoc
          restore-keys: |
            ${{ runner.os }}-

      - name: Instalar dependencias
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages(c("BETS", "usethis", "rsconnect", "shinydashboardPlus", "golem", "plotly"), type = "binary")
        shell: Rscript {0}
      
      - name: Instalar bs4Dash do github
        run: |
          install.packages("devtools")
          devtools::install_github("RinteRface/bs4Dash")
        shell: Rscript {0}
      
      - name: Atualizando dados
        run: |
          source('data-raw/series.R')
        shell: Rscript {0}
      
      - name: Conectando ao ShinyApps
        env:
          SHINY_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          shiny_token = Sys.getenv("SHINY_TOKEN")
          shiny_secret = Sys.getenv("SHINY_SECRET")
          rsconnect::setAccountInfo('albersonmiranda', token = shiny_token, secret = shiny_secret)
        shell: Rscript {0}

      - name: Deploy to ShinyApps
        run: |
          rsconnect::deployApp(forceUpdate = getOption("rsconnect.force.update.apps", TRUE))
        shell: Rscript {0}
